### ISSUE TITLE
Not sure if an issue but...

### ISSUE THREAD

**Issue by Gronfi** [VincentGsell/Gx#1]
in the body of the procedure from the base class 'procedure TCustomGxGraphItem.InputProcess(var InPuData: TGxGraphInputData)' there is a reference to a class that inherits from it, so it looks like a design issue, or something that should be solved at the class that inherits from it.

**Comment by VincentGsell** [comment]
Hi,
Yes and no...In fact, I do this willingly to have all the code temporary at
one area : It is currently just "r&d".
You can move the "if" in TGxGraphShapeItem, but then, you'll have to make
something with a "inherited" at the end of the override method and copy the
beginning code (Hittest and so on) This is worth imho.
In fact, to get a good design, we have certainly to introduce a new class...
thanks for your interests.

N.b. : I'm currently redesign the stuff, to get advantage of GPU and above
all, to replace the famous "geomtry.transformeinverse" by matrix
processing. So it will change a lot.
